[package]
name = "gym"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
socha-client-2022 = {path="../socha-client-rust-2022"}
client = {path="../client"}