name: Rust

on:
  push:
    branches: '**'
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Add targets
      run: rustup target add x86_64-unknown-linux-musl
    
    - name: Build
      run: RUSTFLAGS="-C target-cpu=broadwell -C overflow-checks=no -C lto=fat -C embed-bitcode=y" cargo build --target=x86_64-unknown-linux-musl --workspace --release --out-dir=./target
    
    - name: Run tests
      run: cargo test --verbose
